<div id="sg-shipping">
    <div style="display: none;" class="sg-var" data-name="swift_gift">
        <form id="sg-info-form" action="/sggift/onepage/saveGift" method="POST">
            <fieldset>
                <h3>Gift information</h3>
                <ul>
                    <li class="fields">
                        
                        <div class="field">
                            <label for="sgshipping:country_id" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                            <div class="input-box">
                                <?php echo $this->getCountryHtmlSelect('sgshipping') ?>
                            </div>
                        </div>

                        <div class="field">
                            <label for="sgshipping:region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                            <div class="input-box">
                                <select id="sgshipping:region_id" name="sgshipping[region_id]" title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>" class="validate-select" style="display:none;">
                                    <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                                </select>
                                <script type="text/javascript">
                                 //<![CDATA[
                                 $('sgshipping:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                                 //]]>
                                </script>
                                <input type="text" id="sgshipping:region" name="sgshipping[region]" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"  title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />
                            </div>                            
                        </div>
                        
                        

                        
                        <div class="field">
                            <label class="required">Your name</label>:<br>
                            <div class="input-box">
                                <input type="text" name="name" value="" class="input-text required-entry" /><br>
                            </div>
                        </div>
                        <div class="field">
                            <label class="required">Message</label>
                            <div class="input-box">
                                <textarea name="message" class="textarea required-entry"></textarea>
                            </div>
                        </div>
                    </li>
                </ul>
            </fieldset>
            <div id="sg-buttons-container" class="buttons-set">
                <button id="shipping-sg-submit-btn" type="submit" class="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Continue')) ?>"><span><span><?php echo $this->__('Continue') ?></span></span></button>
                <span id="sg-please-wait" class="please-wait" style="display:none;">
                    <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo Mage::helper('core')->quoteEscape($this->__('Loading next step...')) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Loading next step...')) ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
                </span>
            </div>
        </form>
    </div>
    <div style="display: none;" class="sg-var" data-name="default">
        <?php echo $this->getChildHtml('sg.checkout.onepage.shipping.default') ?>
    </div>
</div>

<script type="text/javascript">
 var sgShippingRegionUpdater = new RegionUpdater('sgshipping:country_id', 'sgshipping:region', 'sgshipping:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'billing:postcode');
</script>
